"""ner标签的字符串常量
"""
LABEL_RELATED_PARTY = "关联方"
LABEL_AMOUNT = "金额"
LABEL_ATTR_NOUN = "属性名词"
LABEL_OCCURRENCE_DATE = "发生时间"
LABEL_DISCLOSE_DATE = "披露时间"
LABEL_DEAL_TYPE = "交易类型"
LABEL_BUSINESS_PROF = "融资方标签"